home:
  link_rails: "https://www.railstutorial.org/"
help:
  link_rails: "https://www.railstutorial.org/help"
_footer:
  link_rails: "https://www.railstutorial.org/help"
  link_admin: https://www.michaelhartl.com/
